version: '3.8'

services:
  neo4j:
    image: neo4j:5.22.0
    expose:
      - "7474"
      - "7687"
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=neo4j/password123
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    restart: unless-stopped

  graph:
    image: zepai/graphiti:latest
    expose:
      - "8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password123
      - PORT=8000
    restart: unless-stopped
    depends_on:
      - neo4j

volumes:
  neo4j_data:
